
#pragma push_macro("PARTITION_BLOCKED_GEN_TYPE_1")
#pragma push_macro("PARTITION_BLOCKED_GEN_TYPE_2")
#pragma push_macro("PARTITION_BLOCKED_GEN_TYPE_3")
#pragma push_macro("PARTITION_BLOCKED_GEN_VECTOR_LEN")
#pragma push_macro("PARTITION_BLOCKED_GEN_SUFFIX")
#pragma push_macro("PARTITION_BLOCKED_GEN_FUNCTION_ATTRIBUTES")
#pragma push_macro("PARTITION_BLOCKED_GEN_EXPAND")
#pragma push_macro("PARTITION_BLOCKED_GEN_EXPAND_TYPE")
#pragma push_macro("_TYPE_V")
#pragma push_macro("_TYPE_I")
#pragma push_macro("_TYPE_AD")
#pragma push_macro("partition_blocked_serial")
#pragma push_macro("partition_blocked_auto_serial")
#include "partition_blocked_gen_undef.h"
